apiVersion: v1
kind: Secret
metadata:
  name: {{ include "air-monitor-ingestor.fullname" . }}
  labels:
    {{- include "air-monitor-ingestor.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  MQTT_BROKER_URL: {{ .Values.secrets.mqttBrokerUrl | quote }}
  MQTT_USERNAME: {{ .Values.secrets.mqttUsername | quote }}
  MQTT_PASSWORD: {{ .Values.secrets.mqttPassword | quote }}
  SUBSCRIPTION: {{ .Values.secrets.subscription | quote }}
