image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

secrets:
  databaseUrl: ""
  mqttBrokerUrl: ""
  mqttUsername: ""
  mqttPassword: ""
  subscription: ""

replicaCount: 1

resources: {}
